version: '3.1'

services:
  postgres_db:
    container_name: recipebuilder-pg-db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: recipebuilderdb
    volumes:
    - mypgdata:/var/lib/postgres/data

volumes:
  mypgdata: {}
